// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { Button } from "@/components/ui/button";
import { FileIcon, HeartIcon } from "lucide-react";
import Link from "next/link";
import { SideBar } from "./side-bar";

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto pt-12">
      <div className="flex gap-8">
        <SideBar />

        <div className="w-full">{children}</div>
      </div>
    </main>
  );
}
